name: whatsapp_bot_flutter
description: Whatsapp bot using puppeteer and whatsapp web scraping with flutter desktop/web and dart projects support
version: 0.1.0
homepage: https://github.com/rohitsangwan01/whatsapp_bot_flutter
repository: https://github.com/rohitsangwan01/whatsapp_bot_flutter
issue_tracker: https://github.com/rohitsangwan01/whatsapp_bot_flutter/issues

environment:
  sdk: ">=2.18.2 <4.0.0"

dependencies:
  zxing2: ^0.2.0
  http: ^0.13.5
  puppeteer: ^3.0.0
  flutter_inappwebview: ^6.0.0-beta.22

dev_dependencies:
  lints: ^2.0.1

# platforms:
#   web:
#   android:
#   ios:
#   windows:
#   macos:
#   linux:
